# .drone.yml
kind: pipeline
type: docker
name: default
workspace:
  path: /src
trigger:
  branch: [main]
  event: [push]
steps:
- name: Website
  image: gmetrixr/baseimage:node-16-dev-v1
  commands:
  #Setup git access for git clone to work
    - mkdir -p $HOME/.ssh
    - ssh-keyscan -t rsa github.com >> $HOME/.ssh/known_hosts
    - echo "$GITHUB_PRIVATE_KEY > $HOME/.ssh/id_rsa"
    - chmod 0600 $HOME/.ssh/id_rsa
  #Actual deploy related commands
    - sudo chown -R node .
    - cd gmetri-help
    - pnpm install
    - pnpm deploy
  environment:
    USE_SSH: true
    GIT_USER: $DRONE_COMMIT_AUTHOR
    GITHUB_PRIVATE_KEY: git_deploy_private_key_help
