# .drone.yml
kind: pipeline
type: docker
trigger:
  branch: [main]
  event: [push]
- name: Website
  image: gmetrixr/baseimage:node-16-dev-v1
  commands:
    - cd gmetri-help
    - p i
    - p deploy
  environment:
    USE_SSH: true
    GIT_USER: $DRONE_COMMIT_AUTHOR
