# .drone.yml
kind: pipeline
type: docker
name: default
workspace:
  path: /src
trigger:
  branch: [main]
  event: [push]
steps:
- name: Website
  image: gmetrixr/baseimage:node-16-dev-v1
  commands:
    - sudo chown -R node .
    - cd gmetri-help
    - pnpm install
    - pnpm deploy
  environment:
    USE_SSH: true
    GIT_USER: $DRONE_COMMIT_AUTHOR
